_target_: diffusion_policy.workspace.train_diffusion_transformer_lowdim_workspace.TrainDiffusionTransformerLowdimWorkspace
action_dim: 12
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 4096
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: true
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 12
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2023.01.16-20.11.42_train_diffusion_transformer_cyber_lowdim
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_diffusion_transformer_lowdim
  - legged_lowdim
  - default
multi_run:
  run_dir: data/outputs/2023.01.16/20.11.42_train_diffusion_transformer_cyber_lowdim
  wandb_name_base: 2023.01.16-20.11.42_train_diffusion_transformer_cyber_lowdim
n_action_steps: 4
n_latency_steps: 0
n_obs_steps: 8
name: train_diffusion_transformer_lowdim
obs_as_cond: true
obs_dim: 45
optimizer:
  betas:
  - 0.9
  - 0.95
  learning_rate: 0.0001
  weight_decay: 0.001
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_transformer_lowdim_policy.DiffusionTransformerLowdimPolicy
  action_dim: 12
  horizon: 12
  model:
    _target_: diffusion_policy.model.diffusion.transformer_for_diffusion.TransformerForDiffusion
    causal_attn: true
    cond_dim: 45
    horizon: 12
    input_dim: 12
    n_cond_layers: 0
    n_emb: 128
    n_head: 4
    n_layer: 2
    n_obs_steps: 8
    obs_as_cond: true
    output_dim: 12
    p_drop_attn: 0.3
    p_drop_emb: 0.0
    time_as_cond: true
    separate_goal_conditioning: true
  n_action_steps: 4
  n_obs_steps: 8
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 10
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 10
  obs_as_cond: true
  obs_dim: 45
  pred_action_steps_only: false
pred_action_steps_only: false
task:
  action_dim: 12
  dataset:
    _target_: diffusion_policy.dataset.cyber_dataset.CyberDogDataset
    horizon: 12
    max_train_episodes: 90
    pad_after: 7
    pad_before: 1
    seed: 42
    val_ratio: 0.02
    zarr_path: recorded_data_5_skills_large.zarr
  env_runner:
    _target_: diffusion_policy.env_runner.legged_runner.LeggedRunner
    agent_keypoints: false
    fps: 10
    keypoint_visible_rate: 1.0
    legacy_test: true
    max_steps: 300
    n_action_steps: 4
    n_envs: null
    n_latency_steps: 0
    n_obs_steps: 8
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    past_action: false
    test_start_seed: 100000
    train_start_seed: 0
  keypoint_dim: 2
  name: legged_lowdim
  obs_dim: 45
task_name: legged_lowdim
training:
  checkpoint_every: 10
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 10000
  max_train_steps: null
  max_val_steps: null
  num_epochs: 1000
  resume: true
  rollout_every: 3
  sample_every: 3
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 10
val_dataloader:
  batch_size: 2048
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: false